# global tool versions go here
# you can set these with `mise use -g`
[tools]
# Languages
go = "latest"
node = 'lts'
pnpm = "11"
uv = "latest"

# Tools
"github:swamp-club/swamp" = "latest"
graphite = "latest"
iam-policy-json-to-terraform = "latest"
"pipx:httpie" = "latest"
"pipx:pgcli" = "latest"
terraform = "latest"
terraform-docs = "latest"

# For vim: LSP, linters, null-ls tools and more
actionlint = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@astrojs/language-server" = "latest"
"pipx:ansible-lint" = "latest"
"npm:bash-language-server" = "latest"


"npm:dockerfile-language-server-nodejs" = "latest"
"github:editorconfig-checker/editorconfig-checker" = { version = "latest", rename_exe = "editorconfig-checker" }
"npm:emmet-ls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"golangci-lint" = "latest"
"go:github.com/hashicorp/hcl/v2/cmd/hclfmt" = "latest"
"github:redhat-developer/vscode-xml" = { version = "latest", rename_exe = "lemminx" }
"lua-language-server" = "latest"
marksman = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:pyright" = "latest"
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
taplo = "latest"
terraform-ls = "latest"
tflint = "latest"
tinymist = "latest"
"npm:yaml-language-server" = "latest"
"npm:typescript-language-server" = "latest"

[tools."npm:@vue/language-server"]
version = "latest"
# Adding @vue/typescript-plugin as direct dependency for neovim lsp.lua to work.
pnpm_args = "@vue/typescript-plugin"

[tools."npm:vscode-langservers-extracted"]
version = "latest"
# Use hoisted linker. Otherwise the binary won't work.
pnpm_args = "--config.node-linker=hoisted"

[settings]
# read version files used by other version managers, such as .nvmrc
idiomatic_version_file_enable_tools = [
  'node',
  'npm',
  'pnpm',
  'python',
  'terraform',
]

lockfile = true

# env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`

[settings.status]
show_env = false
show_tools = false

[settings.npm]
package_manager = "pnpm"
