gui:
  nerdFontsVersion: "3"

os:
  openLink: "nu -c 'start {{link}}'"

git:
  overrideGpg: true # My gpg won't show a password prompt. lg disable some features if I am on gpg
  diffRenderers:
    - colorArg: never
      command: delta --dark --paging=never
    - command: difft --color=always --display=inline --syntax-highlight=off
      type: extDiff
